Mabinogi/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from blog.feeds import AllPostsRssFeed
import xadmin

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='base_html.html'), name='main_page'),
    url(r'^blog/', include('apps.blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

apps/blog/urls.py
__author__ = 'oldpan'
__date__ = '2017/8/11 9:37'


from django.conf.urls import url
from blog.views import BlogView, ArticleView, ArchivesView, CategoryView, TagView

app_name = 'blog'

urlpatterns = [
    url(r'^$', BlogView.as_view(), name='blog_page'),
    url(r'^post/(?P<pk>[0-9]+)/$', ArticleView.as_view(), name='article_page'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', ArchivesView.as_view(), name='archives_page'),
    url(r'^category/(?P<pk>[0-9]+)/$', CategoryView.as_view(), name='category_page'),
    url(r'^tag/(?P<pk>[0-9]+)/$', TagView.as_view(), name='tag_page'),
]

templates/includes/top_menu.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'main_page' %}"><strong>OLDPAN</strong></a>
    </div>
      <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav">
        <li><a href="{% url 'blog:blog_page' %}"><strong>博客</strong></a></li>
        <li><a href="#"><strong>游戏</strong></a></li>
        <li><a href="#"><strong>推荐书籍</strong></a></li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><strong>测试</strong>
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">待开发1</a></li>
          <li><a href="#">待开发2</a></li>
          <li><a href="#">待开发3</a></li>
        </ul>
      </li>
    </ul>
      <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
      </div>
  </div>
</nav>
<hr><br>