Mabinogi/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from blog.feeds import AllPostsRssFeed
import xadmin

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='base_html.html'), name='main_page'),
    url(r'^blog/', include('apps.blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

apps/blog/urls.py
__author__ = 'oldpan'
__date__ = '2017/8/11 9:37'


from django.conf.urls import url
from blog.views import BlogView, ArticleView, ArchivesView, CategoryView, TagView

app_name = 'blog'

urlpatterns = [
    url(r'^$', BlogView.as_view(), name='blog_page'),
    url(r'^post/(?P<pk>[0-9]+)/$', ArticleView.as_view(), name='article_page'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', ArchivesView.as_view(), name='archives_page'),
    url(r'^category/(?P<pk>[0-9]+)/$', CategoryView.as_view(), name='category_page'),
    url(r'^tag/(?P<pk>[0-9]+)/$', TagView.as_view(), name='tag_page'),
]

apps/comments/models.py
from django.db import models
from blog.models import Blog


class Comment(models.Model):
    blog = models.ForeignKey(Blog, verbose_name=u"博客")
    name = models.CharField("称呼", max_length=18)
    email = models.EmailField("邮箱", max_length=50)
    content = models.TextField()
    created_time = models.DateTimeField("发布时间", auto_now_add=True)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.content[:20]

    class Meta:
        verbose_name = "文章评论"
        verbose_name_plural = verbose_name

templates/search/search.html
{% extends 'blog_page.html' %}
{% load highlight %}


 {% block main %}
            <main class="col-md-6">
                {% if query %}
                {% for result in page.object_list %}
                <article class="result.object result.object-{{ result.object.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a style="color: rgb(81,153,107);font-family: 'Adobe 楷体 Std R'" href="{{ result.object.get_absolute_url }}"><h2><strong>{% highlight result.object.title with query %}</strong></h2></a>
                        </h1>
                        <div class="entry-meta">
                            <button class="btn btn-primary btn-xs"><a style="color: white;font-family: 'Times New Roman';" href="{% url 'blog:category_page' result.object.category.pk %}">{{  result.object.category.name  }}</a></button>
                            <button class="btn btn-success btn-xs"><a style="color: white;font-family: 'Times New Roman';"  href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{ result.object.created_time }}</time></a></button>
                            <button class="btn btn-info btn-xs"><a style="color: white;font-family: 'Times New Roman';"  href="#">{{ result.object.author }}</a></button>
                            <button class="btn btn-warning btn-xs"><a style="color: white;font-family: 'Times New Roman';"  href="{{ result.object.get_absolute_url }}">{{ result.object.comment_set.count }} 评论</a></button>
                            <button class="btn btn-danger btn-xs"><a style="color: white;font-family: 'Times New Roman';"  href="{{ result.object.get_absolute_url }}">{{ result.object.views }} 阅读</a></button>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{% highlight result.object.content with query %} </p>
                    </div>
                </article>
                {% empty %}
                    <div class="no-result.object">没有搜索到的结果！</div>
                {% endfor %}

              {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}
                        <a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous
                    {% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next
                    &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
            {% else %}
                请输入搜索关键词，例如 django
            {% endif %}

            </main>
        {% endblock main %}