Mabinogi/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from blog.feeds import AllPostsRssFeed
import xadmin

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='base_html.html'), name='main_page'),
    url(r'^blog/', include('apps.blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

apps/blog/urls.py
__author__ = 'oldpan'
__date__ = '2017/8/11 9:37'


from django.conf.urls import url
from blog.views import BlogView, ArticleView, ArchivesView, CategoryView, TagView

app_name = 'blog'

urlpatterns = [
    url(r'^$', BlogView.as_view(), name='blog_page'),
    url(r'^post/(?P<pk>[0-9]+)/$', ArticleView.as_view(), name='article_page'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', ArchivesView.as_view(), name='archives_page'),
    url(r'^category/(?P<pk>[0-9]+)/$', CategoryView.as_view(), name='category_page'),
    url(r'^tag/(?P<pk>[0-9]+)/$', TagView.as_view(), name='tag_page'),
]

apps/comments/urls.py
__author__ = 'oldpan'
__date__ = '2017/8/14 16:31'

from django.conf.urls import url
from .views import CommentView


app_name = 'comments'

urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', CommentView.as_view(), name='post_comment'),
]

templates/article_page.html
{% extends 'blog_page.html' %}
{% load staticfiles %}
{% block title %}{{ post.title }}{% endblock %}

        {% block main %}
            <main class="col-md-6">
                <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a style="color: black;font-family: 'Microsoft YaHei UI'" href="#"><h2><strong>{{ post.title }}</strong></h2></a>
                        </h1>
                        <div class="entry-meta">
                            <button class="btn btn-primary btn-xs"><a style="color: white;font-family: 'Times New Roman';" href="#">{{ post.category.name }}</a></button>
                            <button class="btn btn-success btn-xs"><a style="color: white;font-family: 'Times New Roman';"  href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{ post.created_time }}</time></a></button>
                            <button class="btn btn-info btn-xs"><a style="color: white;font-family: 'Times New Roman';"  href="#">{{ post.author }}</a></button>
                            <button class="btn btn-warning btn-xs"><a style="color: white;font-family: 'Times New Roman';"  href="#">4 评论</a></button>
                            <button class="btn btn-danger btn-xs"><a style="color: white;font-family: 'Times New Roman';"  href="#">{{ post.views }} 阅读</a></button>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{ post.content|safe }}
                    </div>
                </article>

            <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>说点什么</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                      {% csrf_token %}
                      <div class="row">
                        <div class="col-md-4">
                          <label for="{{ form.name.id_for_label }}">你的名字：</label>
                          {{ form.name }}
                          {{ form.name.errors }}
                        </div>
                        <div class="col-md-4">
                          <label for="{{ form.email.id_for_label }}">你的邮箱：</label>
                          {{ form.email }}
                          {{ form.email.errors }}
                        </div>
                        <div class="col-md-4">
                          <label for="{{ form.url.id_for_label }}">你的个人网址L：</label>
                          {{ form.url }}
                          {{ form.url.errors }}
                        </div>
                        <div class="col-md-12">
                          <label for="{{ form.text.id_for_label }}">你的评论：</label>
                          {{ form.content }}
                          {{ form.content.errors }}
                          <button type="submit" class="comment-btn">发出去</button>
                        </div>
                      </div>    <!-- row -->
                    </form>
                    <ul class="comment-list list-unstyled">
                      {% for comment in comment_list %}
                      <li class="comment-item">
                        <span class="nickname" style="font-family: 'Microsoft YaHei UI'">{{ comment.name }}</span>
                        <time class="submit-date" style="font-family: 'Microsoft YaHei UI'">{{ comment.created_time }}</time>
                        <div class="text">
                          {{ comment.content }}
                        </div>
                      </li>
                      {% empty %}
                      暂无评论
                      {% endfor %}
                    </ul>
                </section>
            </main>
            {% endblock main %}

            {% block catalogue %}
                <div class="widget widget-content">
                    <h3 class="widget-title" style="color:black;font-family: 'Microsoft YaHei UI'"><strong>文章目录</strong></h3>
                        {{ post.toc|safe }}
                </div>
            {% endblock %}

templates/base_html.html
{#base_page : the first page to show when open the website#}
<!DOCTYPE html>
<html lang="zh-Hans">
{% load staticfiles %}

<head>
    <title>{% block title %}Oldpan's home{% endblock %}</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">
    <link rel="stylesheet" href="{% static 'css/tagcloud.css' %}">

    <!-- js -->
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
    <script src="{% static 'js/tagcloud.min.js' %}"></script>
</head>

{% include "includes/top_menu.html" %}

<div class="jumbotron text-center" style="padding-bottom: 20px;padding-top: 28px;">
 <div class="container">
    <div class="row">
        <div class="col-md-2">
            <img src="{% static 'img/head_picture.JPG' %}" class="img-circle img-responsive"/>
        </div>
        <div class="col-md-5 text-center">
            <h1><strong>{OLDPAN}</strong></h1>
            <h3>Blogger & Coder</h3>
        </div>
        <div class="col-md-5">
            <h3>WHO AM I:</h3>
            <h4>&#12288 西电研究生。
                主攻机器学习以及图像方面的深度<br>学习，
                业余linux服务器，爱好摄影、电脑主机游戏，
                欢迎志同道合的朋友前来骚扰
                <br>
                <i><strong>coolesthacker@163.com</strong></i>
                <br>
                <i><strong>QQ:295484914</strong></i>
            </h4>

        </div>
    </div>
   </div>
</div>




<body>
{% block body %}
{% endblock %}


<script type="text/javascript">
    tagcloud();
</script>
</body>

</html>

templates/blog_page.html
{#The blog page which shows articles #}
{% extends "base_html.html" %}
{% load staticfiles %}
{% load blog_tags %}

{% block title %}Oldpan的博客{% endblock %}

{% block body %}
<div class="content-body">

    <div class="container-fluid">
        <div class="row">
            <left-side class="col-md-2">
    {#                leave to fill content#}
            </left-side>
         {% block main %}
            <main class="col-md-6">
                {% for post in post_list %}
                <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a style="color: black; font-family: 'Microsoft YaHei UI'" href="{{ post.get_absolute_url }}"><h2><strong>{{ post.title }}</strong></h2></a>
                        </h1>
                        <div class="entry-meta">
                            <button class="btn btn-primary btn-xs"><a style="color: white;font-family: 'Microsoft YaHei UI';" href="#">{{ post.category.name }}</a></button>
                            <button class="btn btn-success btn-xs"><a style="color: white;font-family: 'Times New Roman';"  href="#"><time class="entry-date">{{ post.created_time }}</time></a></button>
                            <button class="btn btn-info btn-xs"><a style="color: white;font-family: 'Times New Roman';"  href="#">{{ post.author }}</a></button>
                            <button class="btn btn-warning btn-xs"><a style="color: white;font-family: 'Times New Roman';"  href="#">4 评论</a></button>
                            <button class="btn btn-danger btn-xs"><a style="color: white;font-family: 'Times New Roman';"  href="#">{{ post.views }} 阅读</a></button>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.abstract }}</p>
                    </div>
                </article>

                {% empty %}
                    <div class="no-post">暂时还没有发布的文章！</div>
                {% endfor %}

                <div style="text-align: center">
                {% if is_paginated %}
                <div class="pagination pagination-sm">
                      {% if first %}
                          <li><a href="?page=1">1</a></li>
                      {% endif %}
                      {% if left %}
                        {% if left_has_more %}
                            <span>...</span>
                        {% endif %}
                        {% for i in left %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                      {% endif %}
                        <li class="active"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                      {% if right %}
                        {% for i in right %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                        {% if right_has_more %}
                            <span>...</span>
                        {% endif %}
                      {% endif %}
                      {% if last %}
                          <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
                      {% endif %}
                    </div>
                    {% endif %}
                 </div>
            </main>

        {% endblock main %}

            <div class="col-md-3">
                <ul class="list-group">
                    <li class="list-group-item"><strong>最新文章</strong></li>
                    {% get_recent_posts as recent_post_list %}
                        {% for post in recent_post_list %}
                      <li class="list-group-item">
                        <span class="badge">{{ post.views }}</span>
                          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                          {% empty %}
                           暂无文章
                        {% endfor %}
                      </li>
                    <li class="list-group-item"><strong>分类</strong></li>
                    {% get_categories as category_list %}
                    {% for category in category_list %}
                      <li class="list-group-item">
                        <span class="badge">{{ category.num_posts }}</span>
                          <a href="{% url 'blog:category_page' category.pk %}">{{ category.name }}</a>
                      </li>
                    {% empty %}
                    暂无分类
                    {% endfor %}
                </ul>

                <div class="widget widget-archives" style="padding-top: 0px;">
                    <h3 style="color:black;font-family: 'Microsoft YaHei UI'"  class="widget-title"><strong>归档</strong></h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives_page' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                        </li>
                        {% empty %}
                        暂无归档
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 style="color:black;font-family: 'Microsoft YaHei UI'" class="widget-title"><strong>标签云</strong></h3>
                    <div class="tagcloud">
                  {% get_tags as tag_list %}
                     {% for tag in tag_list %}
                          <a href="{% url 'blog:tag_page' tag.pk %}">{{ tag.name }}</a>
                     {% empty %}
                          <a href="#">暂无标签！</a>
                    {% endfor %}
                    </div>
                </div>

                <div class="rss">
                    <a style="font-family: 'Microsoft YaHei UI'; color: black" href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS订阅</a>
                </div>

                <div style="padding-top:30px;">
                    <ul class="list-group">
                        <li class="list-group-item">Advertise</li>
                        <li class="list-group-item">
                            <a href="https://www.vultr.com/?ref=7204333"><img src="https://www.vultr.com/media/banner_3.png" width="300" height="250"></a>
{#                            <a href=""><img src="{% static 'img/vultr_banner.png' %}" class="img-responsive" /></a>#}
                            <br />
{#                            <a href="#"><img src="assets/img/ad2.jpg" class="img-responsive" /></a>#}
                        </li>
                    </ul>
                </div>

                <div style="padding-top:30px;">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                        <h3 class="panel-title">全站搜索</h3>
                        </div>
                        <div class="panel-body">
                        <input type="text" class="form-control" placeholder="搜索功能正在开发" />
                         <hr />
                         <a href="#" class="btn btn-info btn-sm btn-block" >搜吧</a>
                       </div>
                    </div>
                </div>
            </div>


{#            <aside class="col-md-3">#}
{#            {% block catalogue %}#}
{#                {% endblock %}#}
{#                <div class="widget widget-recent-posts">#}
{#                    <h2 style="color:black;font-family: 'Microsoft YaHei UI'" class="widget-title"><strong>最新文章</strong></h2>#}
{#                    {% get_recent_posts as recent_post_list %}#}
{#                    <ul>#}
{#                        {% for post in recent_post_list %}#}
{#                        <li>#}
{#                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>#}
{#                        </li>#}
{#                        {% empty %}#}
{#                        暂无文章#}
{#                        {% endfor %}#}
{#                    </ul>#}
{#                </div>#}
{#                <div class="widget widget-archives">#}
{#                    <h3 style="color:black;font-family: 'Microsoft YaHei UI'"  class="widget-title"><strong>归档</strong></h3>#}
{#                    {% archives as date_list %}#}
{#                    <ul>#}
{#                        {% for date in date_list %}#}
{#                        <li>#}
{#                            <a href="{% url 'blog:archives_page' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>#}
{#                        </li>#}
{#                        {% empty %}#}
{#                        暂无归档#}
{#                        {% endfor %}#}
{#                    </ul>#}
{#                </div>#}
{##}
{#                <div class="widget widget-category">#}
{#                    <h3 style="color:black;font-family: 'Microsoft YaHei UI'"  class="widget-title"><strong>分类</strong></h3>#}
{#                    {% get_categories as category_list %}#}
{#                    {% for category in category_list %}#}
{#                        >#}
{#                        <a href="{% url 'blog:category_page' category.pk %}">{{ category.name }} <span class="badge">{{ category.num_posts }}</span></a><br>#}
{#                    {% empty %}#}
{#                    暂无分类#}
{#                    {% endfor %}#}
{#                </div>#}
{##}
{#                <div class="widget widget-tag-cloud">#}
{#                    <h3 style="color:black;font-family: 'Microsoft YaHei UI'" class="widget-title"><strong>标签云</strong></h3>#}
{#                    <div class="tagcloud">#}
{#                  {% get_tags as tag_list %}#}
{#                     {% for tag in tag_list %}#}
{#                          <a href="{% url 'blog:tag_page' tag.pk %}">{{ tag.name }}</a>#}
{#                     {% empty %}#}
{#                          <a href="#">暂无标签！</a>#}
{#                    {% endfor %}#}
{#                    </div>#}
{#                </div>#}
{##}
{#                <div class="rss">#}
{#                    <a style="font-family: 'Microsoft YaHei UI'; color: black" href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS订阅</a>#}
{#                </div>#}
{#            </aside>#}

        <right-side class="col-md-1">
{#            leave to fill content#}
        </right-side>
        </div>
    </div>
</div>

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright"><strong>@copyright 2017 - Design by</strong><a style="color: #31b0d5;" href="{% url 'main_page' %}"><strong> Oldpan</strong></a>

                </p>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'js/script.js' %}"></script>

{% endblock %}